### ISSUE TITLE
Option to download from CLI?!

### ISSUE THREAD

**Issue by IGRACH** [defunkt/gist#192]
Is there a option to download gists from CLI, or I'm a missing something?

**Comment by ConradIrwin** [comment]
Not yet, but it's been requested a few times. If you wanted to implement it as `gist -r <url|id>`, a lot of people would be grateful :).

**Comment by IGRACH** [comment]
Well I don't want to be blunt but is't that suppose to be core functionality?

**Comment by Wolf480pl** [comment]
I don't know Ruby, so as a workaround for this issue I wrote a little wrapper shell script: https://gist.github.com/Wolf480pl/a9f4242524138a0c7cd9
Usage: `gist.sh -r <url>` (`<id>` won't work, any options before `-r` won't work either)
Works best with `alias gist=gist.sh`

**Comment by zakysiak** [comment]
I pulled a request which add option gist -r <url|id>.

**Comment by ConradIrwin** [comment]
We've now had this for a while
