### ISSUE TITLE
contrib: snippet for (basic) Vim integration (WIP)

### ISSUE THREAD

**Issue by blueyed** [defunkt/gist#195]
You might like to add this to the documentation:
https://gist.github.com/blueyed/3445f580a1d91861b245

```
" Paste using [gist-paste](https://github.com/defunkt/gist).
command! -range=% -nargs=* Gistpaste call MyGistpaste(<line1>, <line2>, <f-args>)
fun! MyGistpaste(line1, line2, ...) abort
  " let args = ['-t', &ft]  " overrides -f?!
  let args = []

  " Autoset -f, if it's not given.
  if index(a:000, '-f') == -1
    let fname = fnamemodify(expand('%'), ':t')
    let ext = fnamemodify(fname, ':e')
    if !len(ext)
      let fname .= '.'.&ft
    endif
    let args += ['-f', fname]
  endif

  " Escape args.
  for a in a:000 | let args += [shellescape(a)] | endfor

  let cmd = ':'.a:line1.','.a:line2.'w !gist-paste '.join(args, ' ')
  echo "Executing:" cmd
  exec cmd
endfun
```

**Comment by ConradIrwin** [comment]
The easiest way by far to use this from vim is `<esc>:%!gist`. This then replaces the buffer by a URL, and you can type u to undo the change and get your file back.

What does the snippet do? (I'm not great at reading vim script)

**Comment by blueyed** [comment]
The snippet basically does / wraps this, but also sets `-f` automatically based on the current buffer name (and filetype if there's no extension).
It also supports ranges, so you can visually select a block, and only paste that one.

You could use an additional `!` in your easy example to not replace the buffer's content: `%w!gist`.

**Comment by ConradIrwin** [comment]
Closing this for now as it's not an issue per-se
