### ISSUE TITLE
Gists should not be anonymous by default

### ISSUE THREAD

**Issue by dnrce** [defunkt/gist#196]
Because anonymous gists can't be deleted by the poster, posting an anonymous gist should only be done when explicitly requested. It should not be the default behavior when not logged in.

**Comment by Brottweiler** [comment]
If you enable authentication, they aren't anon by default. For example, if I want to have an anon gist, I am **required** to use the `--anonymous` option.

**Comment by dnrce** [comment]
Right. My assertion is that when one isn't logged in, it should still have to be explicit.

**Comment by ConradIrwin** [comment]
gist is designed to work for not-logged-in users as well as logged in ones, so I don't want to break the gem for them.

Luckily gist uses unguessable URLs by default, so the chances of someone finding stuff you've accidentally gisted is low. (and I'm sure you can reach out to github support to delete really egregious stuff).

**Comment by dnrce** [comment]
It doesn't *break* the gem, it would just require use of the `-a` flag. But I won't argue further.

**Comment by dnrce** [comment]
I will, however, note that this can be fairly important for GitHub Enterprise users.
