### ISSUE TITLE
Documentation incorrect (or maybe just confusing)

### ISSUE THREAD

**Issue by tnrich** [defunkt/gist#197]
From issue #12: 
The syntax to update an existing gist is:
```
gist -u GIST_ID FILE_NAME
```

Yet, this clashes with the only update example in the documentation: 
```
You can update existing gists with -u:

gist lib/gist.rb bin/gist -u 42f2c239d2eb57299408
```

Documentation: https://gist.github.com/cf78cbdb8f003d87808c

**Comment by ConradIrwin** [comment]
Hey @tnrich,

The order of arguments doesn't matter, so the two are saying the same thing.

Conrad

**Comment by tnrich** [comment]
also this same issue exists on documentation found at:

https://github.com/defunkt/gist

**Comment by tnrich** [comment]
Hmm okay, maybe then just separate the two use cases (updating an existing
gist and updating multiple existing gists). It tripped me up as a naive
user...

On Thursday, February 26, 2015, Conrad Irwin <notifications@github.com>
wrote:
> Hey @tnrich,
>
> The order of arguments doesn't matter, so the two are saying the same
thing.
>
> Conrad
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/OrbKcma_QmyuLcQgnQxkXEKRvne74KvJk58YqTHRoTvh1GLAggt2kMspz8U5sI8ZScI7cGzoTeZUDeY85vK5es1CssKWG5rPT2_HFvrJazR76nJL__M29a8OAZsFtjlyKiiGKyceeb9F4yzkPBGCfzF2vNitAQ=s0-d-e1-ft#https://github.com/notifications/beacon/ACmqcXDn-HjWZt1wRrVyPe_VsDZ7Zh_yks5nv42lgaJpZM4Dmoco.gif
>

**Comment by ConradIrwin** [comment]
Feel free to send a pull request to make the docs clearer :).

conrad

**Comment by tnrich** [comment]
Okay, will do!
