### ISSUE TITLE
Please add support for Enterprise Github aka custom url

### ISSUE THREAD

**Issue by dragon788** [defunkt/gist#199]
We use an Enterprise Github instance internally and have no access to the outside world. We are using the excellent 'hub' tool provided by Github and it supports overrides via an environment variable and a .hub/config file, it would be nice if gist would allow the same in its config file.

Our instance has the url as https://github.ourdomain.com/gist/username for gists.

**Comment by akerl** [comment]
This exists: https://github.com/defunkt/gist#github-enterprise

Did you run into issues setting that up?

**Comment by dragon788** [comment]
Holy cow, I had read the entire readme and yet that still didn't stick in
my brain. One thing I did notice upon double checking with the hub
documentation, would it be possible to have gist not only check git hub_url
but also github_host so that I don't have to define it twice, one for each
piece of software when its defining exactly the same thing?

**Comment by akerl** [comment]
I'm not the maintainer, but that's probably something worth making a PR for; it seems sane to me.

**Comment by dragon788** [comment]
Sounds good, I'll see if I can rename this one and then close it when I
make the pull request.
