### ISSUE TITLE
gist --list not showing all gists for user

### ISSUE THREAD

**Issue by flexseth** [defunkt/gist#201]
For instance, gist account:  
https://gist.github.com/srikat

Command
gist --list srikat

Only returns 30 gists, when the account has over 400

**Comment by nik045** [comment]
:+1:

**Comment by Em-AK** [comment]
It looks like [the gist API paginates the response for list requests](https://developer.github.com/v3/gists/#list-gists)

**Comment by ConradIrwin** [comment]
I'd love a pull-request for this :).

**Comment by zmwangx** [comment]
I believe this issue should be closed by #203.
