### ISSUE TITLE
error when using double-quotes

### ISSUE THREAD

**Issue by nguillermin** [defunkt/gist#207]
Was trying to do:

    $ tree . | gist -d "`tree` of lsd_slam_viewer"

but that currently results in

    Error: Got Net::HTTPUnprocessableEntity from gist: {"message":"Validation Failed","errors":[{"resource":"Gist","code":"invalid","field":"description"}],"documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}

The problem seems to be the double-quotes, which I assume come from them being used in the json.

**Comment by ConradIrwin** [comment]
Can you try:

```
tree . | gist 
```

and

```
echo a | gist -d "`tree` of lsd_slam_viewer"
```

Do both fail?

**Comment by nguillermin** [comment]
`tree . | gist` works fine (returns https://gist.github.com/6696052c02d17cccbf52, which I'll leave up for you).

`echo a | gist -d "`tree` of lsd_slam_viewer"` gives me `Error: Got Net::HTTPUnprocessableEntity from gist: {"message":"Validation Failed","errors":[{"resource":"Gist","code":"invalid","field":"description"}],"documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}`

I am quite certain its the double-quotes.

**Comment by ConradIrwin** [comment]
The double quotes that I can see are parsed by bash, and invisible to `gist`.

What's the output of `tree` ?

**Comment by nguillermin** [comment]
Just edited my comment, the code block wasn't showing up correctly because I used backticks and not 4 spaces to delineate a code block.

output of `tree` is 

    .
    ├── android
    │   ├── README.android
    │   ├── android.toolchain.cmake
    │   └── service
    │       ├── CMakeLists.txt
    │       ├── engine
    │       │   ├── AndroidManifest.xml
    │       │   ├── CMakeLists.txt
    │       │   ├── build.xml
    │       │   ├── project.properties
    │       │   ├── res
    │       │   │   ├── drawable
    │       │   │   │   └── icon.png
    │       │   │   ├── layout
    │       │   │   │   └── main.xml
    │       │   │   └── values
    │       │   │       └── strings.xml
    │       │   └── src
    │       │       └── org
    │       │           └── opencv
    │       │               └── engine
    │       │                   ├── HardwareDetector.java
    │       │                   ├── MarketConnector.java
    │       │                   ├── OpenCVEngineInterface.aidl
    │       │                   ├── OpenCVEngineService.java
    │       │                   └── manager
    │       │                       └── ManagerActivity.java
    │       └── readme.txt
    ├── ios
    │   ├── Info.plist.in
    │   ├── build_framework.py
    │   ├── cmake
    │   │   ├── Modules
    │   │   │   └── Platform
    │   │   │       └── iOS.cmake
    │   │   └── Toolchains
    │   │       ├── Toolchain-iPhoneOS_Xcode.cmake
    │   │       └── Toolchain-iPhoneSimulator_Xcode.cmake
    │   └── readme.txt
    ├── linux
    │   └── arm-gnueabi.toolchain.cmake
    ├── osx
    │   ├── Info.plist.in
    │   └── build_framework.py
    ├── readme.txt
    ├── scripts
    │   ├── ABI_compat_generator.py
    │   ├── camera_build.conf
    │   ├── cmake_android_all_cameras.py
    │   ├── cmake_android_arm.sh
    │   ├── cmake_android_mips.sh
    │   ├── cmake_android_service.sh
    │   ├── cmake_android_x86.sh
    │   ├── cmake_arm_gnueabi_hardfp.sh
    │   ├── cmake_arm_gnueabi_softfp.sh
    │   ├── cmake_carma.sh
    │   └── cmake_winrt.cmd
    └── winrt
        ├── arm.winrt.toolchain.cmake
        ├── build_all.bat
        ├── readme.txt
        ├── setup_winrt.bat
        └── setup_winrt.ps1
    
    21 directories, 42 files

**Comment by ConradIrwin** [comment]
In bash backticks take effect even in quotes, so you were trying to do:

```
gist -d ".
├── android
│   ├── README.android
│   ├── android.toolchain.cmake
│   └── service
│       ├── CMakeLists.txt
│       ├── engine
│       │   ├── AndroidManifest.xml
│       │   ├── CMakeLists.txt
│       │   ├── build.xml
│       │   ├── project.properties
│       │   ├── res
│       │   │   ├── drawable
│       │   │   │   └── icon.png
│       │   │   ├── layout
│       │   │   │   └── main.xml
│       │   │   └── values
│       │   │       └── strings.xml
│       │   └── src
│       │       └── org
│       │           └── opencv
│       │               └── engine
│       │                   ├── HardwareDetector.java
│       │                   ├── MarketConnector.java
│       │                   ├── OpenCVEngineInterface.aidl
│       │                   ├── OpenCVEngineService.java
│       │                   └── manager
│       │                       └── ManagerActivity.java
│       └── readme.txt
├── ios
│   ├── Info.plist.in
│   ├── build_framework.py
│   ├── cmake
│   │   ├── Modules
│   │   │   └── Platform
│   │   │       └── iOS.cmake
│   │   └── Toolchains
│   │       ├── Toolchain-iPhoneOS_Xcode.cmake
│   │       └── Toolchain-iPhoneSimulator_Xcode.cmake
│   └── readme.txt
├── linux
│   └── arm-gnueabi.toolchain.cmake
├── osx
│   ├── Info.plist.in
│   └── build_framework.py
├── readme.txt
├── scripts
│   ├── ABI_compat_generator.py
│   ├── camera_build.conf
│   ├── cmake_android_all_cameras.py
│   ├── cmake_android_arm.sh
│   ├── cmake_android_mips.sh
│   ├── cmake_android_service.sh
│   ├── cmake_android_x86.sh
│   ├── cmake_arm_gnueabi_hardfp.sh
│   ├── cmake_arm_gnueabi_softfp.sh
│   ├── cmake_carma.sh
│   └── cmake_winrt.cmd
└── winrt
    ├── arm.winrt.toolchain.cmake
    ├── build_all.bat
    ├── readme.txt
    ├── setup_winrt.bat
    └── setup_winrt.ps1

21 directories, 42 files of lsd_slammer"
```

I'm assuming there's a validation on length of description that this is too long.
