### ISSUE TITLE
unsupported signal SIGPIPE (ArgumentError) on Windows x64 ruby 2.0.0p647

### ISSUE THREAD

**Issue by jeffbonhag** [defunkt/gist#209]
On a clean Ruby 2.0.0p647 install on Windows 10 (64-bit), when I run `gist` I get this error:

    C:\Users\jeff>gist --help
    C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gist-4.4.2/bin/gist:5:in `trap': unsupported signal SIGPIPE (ArgumentError)
            from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gist-4.4.2/bin/gist:5:in `<top (required)>'
            from C:/Ruby200-x64/bin/gist:23:in `load'
            from C:/Ruby200-x64/bin/gist:23:in `<main>'

It happens regardless of the parameters passed to `gist`.

I commented out line 5 in the `gist` executable:

    #trap('PIPE', 'EXIT')

After commenting out this line, `gist` works fine.

**Comment by ConradIrwin** [comment]
@jeffbonhag I'd love a pull request to fix this — it should just be a case of wrapping this line in a `try/catch`. But if there's a better way of testing for SIGPIPE I'd accept that too :).

**Comment by jeffbonhag** [comment]
@ConradIrwin You got it!  I didn't have any ideas how to do it, but now you've given me two.  I'll put together a pull request.
