### ISSUE TITLE
Something went wrong with that request. Please try again

### ISSUE THREAD

**Issue by puneetpandey** [defunkt/gist#215]
I have written a gist with URL as https://gist.github.com/puneetpandey/8e11a24406bf4d6792a5 . Problem is, whenever I am clicking on 'HTTPS' for HTTPS clone URL, I am getting 'Something went wrong with that request. Please try again.'
Attached is the screenshot for the same.

![gist-issue](https://cloud.githubusercontent.com/assets/83669/10307396/3590dda8-6c4c-11e5-9ce1-77e7380b53d4.png)

**Comment by puneetpandey** [comment]
I tried creating different gists with different names but problem appears for all

**Comment by akerl** [comment]
That seems like an issue with GitHub itself; this is a gem that interacts with GitHub's API via the command line. You probably want to contact GitHub themselves: https://github.com/contact

**Comment by puneetpandey** [comment]
Thank you so much for pointing me into the right direction. I will bring
this concern into GitHub's notice.

On Tuesday 6 October 2015, Conrad Irwin <notifications@github.com> wrote:

> Closed #215 <https://github.com/defunkt/gist/issues/215>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/defunkt/gist/issues/215#event-428234837>.
>


-- 

*Warm Regards*
*Puneet Pandey*
*Technical Specialist*
My Website <http://puneetpandey.com/>


[image: --]

Puneet Pandey
[image: http://]about.me/puneetpandey
<http://about.me/puneetpandey>
  Linkedin <http://in.linkedin.com/in/puneetonrails> | Github
<https://github.com/puneetpandey>
