### ISSUE TITLE
copy2gist feedback

### ISSUE THREAD

**Issue by silverbux** [defunkt/gist#216]
hi @defunkt i got inspired by your "gist" repo so i decided to code this, still on its early stage
https://github.com/silverbux/copy2gist

im just wondering if you could give some feedback on it, and suggestions on how could i automate getting user token part. 

thanks in advance :)

**Comment by ConradIrwin** [comment]
@silverbux Great work!

We get the token using the github API. You can see the code here: https://github.com/defunkt/gist/blob/master/lib/gist.rb#L298-L305

Conrad
