### ISSUE TITLE
Default Title is '-'

### ISSUE THREAD

**Issue by ajmichels** [defunkt/gist#220]
Maybe I am just missing something but when I create a new gist from STDIN or my clipboard the name of the gist ends up being "-" (hyphen). There are a couple issues with this.

1. It isn't unique, making it harder to identify distinct gists in various situations.
2. It is really short making for a very small hit area for clicking on the title when viewing it on GitHub.
3. It doesn't seem that there is currently any way in GitHub to change this title after it has been created.

Perhaps a simple solution would be to make the title a UUID or a hash. Just something unique.

Adding a new parameter to allow for someone to set this value manually would be nice too, but I think addressing the hyphen issue (the default) is of more immediate importance. I wouldn't want to have to specify a title every time since it would make creating a quick gist more cumbersome.

**Comment by ConradIrwin** [comment]
You can give it a name using the `-f` parameter:

````
$ gist -f a.js
(type a gist. <ctrl-c> to cancel, <ctrl-d> when done)
````

I don't think a hash will help that much, as there's already one in the URL that you could have been using :).

If you want to be able to edit gists, you need to log into the gist tool:

````
$ gist --login
````

**Comment by ajmichels** [comment]
Thanks for responding.

I see, renaming the Gist via the GitHub interface is not very intuitive as you are renaming the "file" rather than the Gist.

I missed the `-f` option. I still think it would be good for this to have a better default than "-". Again, entering a title when I just want to get a snippet to someone really quickly is not ideal.
