### ISSUE TITLE
--shorten not working anymore?

### ISSUE THREAD

**Issue by bpierre** [defunkt/gist#229]
I see no difference with or without the `--shorten` option.

**Comment by tjt263** [comment]
I think the git.io site or API changed slightly.
Pretty sure you just need to swap out:

`GIT_IO_URL       = URI("http://git.io")`
for:
`GIT_IO_URL       = URI("https://git.io/create")`

**Comment by ConradIrwin** [comment]
Please send a pull request :)

**Comment by tjt263** [comment]
I honestly don't know what that means or what it involves; 
I'm sorta new around here. Also it may not even be correct.
Just saying.

**Comment by ConradIrwin** [comment]
welcome! Pull requests are just an easy way for everyone to work on the same code, there are instructions here: https://help.github.com/articles/using-pull-requests/ :). They let everyone fix bugs and add features to the software they care about, so it's a fun skill to have. Let me know if you need more direction.

**Comment by two-dogs** [comment]
https://github.com/defunkt/gist/issues/229#issue-129791242 , second that comment, --shorten does not work here either
