### ISSUE TITLE
[BUG] Arch Installation Errors

### ISSUE THREAD

**Issue by DerekTBrown** [defunkt/gist#230]
Directly after installing, I get the following error:

/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'gist' (>= 0) among 14 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/dbrown/.gem/ruby/2.3.0:/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /home/dbrown/.gem/ruby/2.2.0/bin/gist:22:in `<main>'

**Comment by ConradIrwin** [comment]
This sounds like a problem with your ruby environment, try some of the solutions listed here: http://stackoverflow.com/questions/6278047/could-not-find-rails-0-amongst-gemloaderror.

Good luck!
