### ISSUE TITLE
Support OAuth Device Flow

### ISSUE THREAD

**Issue by colemickens** [defunkt/gist#251]
Please support the OAuth Device Flow.

It's easier for users (especially those with 2FA, which is hopefully everyone) and it doesn't require me to hand you my password...

**Comment by broady** [comment]
Also, please document where I'd put my access token if manually generating.

It says ~/.gist, but I don't know in what format or whether ~/.gist should be a directory.

**Comment by ConradIrwin** [comment]
@colemickens Unfortunately I'm not aware of a better way to run the Oauth flow on Github, but gist does store only an access token (the code is written in ruby, so you should be able to audit what's running on your machine if that's important). 

We use the flow documented by Github here, which supports 2-factor-auth just fine: https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#non-web-application-flow

@broady I've documented how you might do this here: https://github.com/defunkt/gist/#password-less-login. As above, I think for most users this is unnecessary.

**Comment by broady** [comment]
@ConradIrwin, that flow doesn't support FIDO U2F. See https://github.com/github/hub/issues/1621

But thanks for the addition to the docs. It's necessary for more users than you'd think. A lot of corps (including mine -- Google) require 2FA enabled.

**Comment by ConradIrwin** [comment]
Ah! Suddenly Everything Connects. You might want to reach out to Github about making this work over the API (unless there is a way to do it I'm missing) — I'd much rather delegate any need to integrate with USB devices to a browser :)

**Comment by colemickens** [comment]
OAuth2 has a draft standard that is a new flow. It is built specifically for things that are operating in a potentially headless mode where other flows are impractical because hardware device might not have IME, or the requesting application is not the same as localhost (so the browser can't post the token to localhost).

In these cases, some providers, like Azure, support device code flow authorization. In this model, the requesting application creates a "session" with the provider, the provider returns a URL to redirect the user to, and then the client polls another OAuth url until the user visits the URL and completes the flow. It means the token is "polled" and "pulled" down to a given location, while the user may have completed the actual sign in on another machine.

Of course, now that I've typed this out, it doesn't seem like GitHub supports this flow with their OAuth2 endpoint. (Or if they do, they haven't documented it)

**Comment by ConradIrwin** [comment]
Makes sense. I think that approach, or the "redirect to a port on localhost" would both work fine. Pull requests welcome :D
