### ISSUE TITLE
Mac User: why don't have a command to delete a gist?

### ISSUE THREAD

**Issue by suredream** [defunkt/gist#254]
defunkt:

You tool is awesome. But why don't have a command to delete a gist?

**Comment by jmeridth** [comment]
Check out the previous issue #211 and the pull request #222. Definitely suggest reading through previous issues and pull requests before making your own. 

I am not associated to this project but wanted you to be aware that you can pull down that PR's code and use the `--delete` feature now before it is merged.

**Comment by cbandy** [comment]
#222 is merged; this can probably be closed.
