### ISSUE TITLE
document format expected for token file

### ISSUE THREAD

**Issue by gcbw** [defunkt/gist#257]
My organization uses github enterprise with SSO only. I cannot get a token via the API this uses because i cannot log on with a password on github directly.

But it is trivial for me to generate a new token via the webinterface and save it on a file. Just need to document the format on the README.

should it just be the token alone in a file named `~/.gist.server.name`?

**Comment by ConradIrwin** [comment]
Yup! Please send a pull request to add this to the readme :D

Conrad

Sent via Superhuman <https://sprh.mn/?vip=conrad@superhuman.com>

**Comment by gcbw** [comment]
just tried to. But i can't see a valid one :(

tried to log on the public github with no success:
```
$ export GITHUB_URL=https://github.com/

$ gist --login
Obtaining OAuth2 access_token from github.
GitHub username: gcbw
GitHub password:
/usr/local/bin/gist:1654:in `block in login!': Got Net::HTTPForbidden from gist: Cookies must be enabled to use GitHub. (RuntimeError)
	from /usr/local/bin/gist:1614:in `loop'
	from /usr/local/bin/gist:1614:in `login!'
	from /usr/local/bin/gist:1896:in `block (2 levels) in <main>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `block in parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1345:in `order!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1437:in `permute!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1459:in `parse!'
	from /usr/local/bin/gist:1975:in `<main>'
```

**Comment by ConradIrwin** [comment]
The public github instance is configured a little differently to an
on-premise install, `unset GITHUB_URL` to test it. (The code implicitly
assumes that any explicit url is an enterprise install)

Conrad

Sent via Superhuman <https://sprh.mn/?vip=conrad.irwin@gmail.com>

**Comment by gcbw** [comment]
OK. that worked, thanks. I got a file `~/.gist` that contains only the token, no new line.

Tried to create the same. Added my token without newline to `~.gist.server.name` and set `export GITHUB_URL=https://server.name/`

but
```
$ gist -l
Error: Not authenticated. Use 'gist --login' to login or 'gist -l username' to view public gists.
```

**Comment by ConradIrwin** [comment]
I notice that it does this:

        File.expand_path "~/.gist.#{ENV[URL_ENV_NAME].gsub(/[^a-z.]/, '')}"

You may need to use `.gist.httpsserver.name` :/

Conrad

Sent via Superhuman <https://sprh.mn/?vip=conrad.irwin@gmail.com>

**Comment by gcbw** [comment]
👍 
that solves the mystery. Will send a patch for docs. Thanks!

**Comment by gcbw** [comment]
mind if i also patch that line to use:
File.expand_path "~/.gist.#{ENV[URL_ENV_NAME].gsub(/:/, '.').gsub(/[^a-z.]/, '')}"

so the file can be `.gist.https.server.name`?

**Comment by ConradIrwin** [comment]
Sounds good to me — it will cause any other users of enterprise github to
have to re-log in on upgrade, but I posit that upgrading gist is rare, and
there are relatively few such users.



Sent via Superhuman <https://sprh.mn/?vip=conrad.irwin@gmail.com>

**Comment by gcbw** [comment]
https://github.com/defunkt/gist/pull/258
