### ISSUE TITLE
Login with PAT fails

### ISSUE THREAD

**Issue by jasonkarns** [defunkt/gist#264]
```
$ gist --login
Obtaining OAuth2 access_token from github.
GitHub username: jasonkarns
GitHub password: 
/usr/local/bin/gist:1677:in `block in login!': Got Net::HTTPForbidden from gist: {"message":"This API can only be accessed with username and password Basic Auth","documentation_url":"https://developer.github.com/v3/oauth_authorizations/#oauth-authorizations-api"} (RuntimeError)
	from /usr/local/bin/gist:1637:in `loop'
	from /usr/local/bin/gist:1637:in `login!'
	from /usr/local/bin/gist:1919:in `block (2 levels) in <main>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1552:in `block in parse_in_order'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1538:in `catch'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1538:in `parse_in_order'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1532:in `order!'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1626:in `permute!'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/optparse.rb:1648:in `parse!'
	from /usr/local/bin/gist:2002:in `<main>'
```

**Comment by ConradIrwin** [comment]
@jasonkarns what's PAT?

**Comment by jasonkarns** [comment]
Sorry, Personal Access Token:
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

Supposed to be used in place of passwords for all scenarios that require
Basic Auth.

**Comment by ConradIrwin** [comment]
You can probably just put your token into the file `~/.gist` directly: https://github.com/defunkt/gist#login

gist's login command just abstracts away from the process of creating one.

**Comment by jasonkarns** [comment]
PATs are meant specifically to avoid users supplying their passwords to apps directly. gist continuing to require one's master password is a huge security flaw and antipattern.

**Comment by ConradIrwin** [comment]
@jasonkarns The gist command does not require a password. The login functionality simplifies the process of creating a personal access token and writing it to `~/.gist`.

As you already have a personal access token just write it to `~/.gist` and the gist command will happily use it.

I'd be happy to accept code/documentation changes that make it easier for someone like you who has a token already to use it for gist. Maybe `gist --save-token X` (though that would log it into your `~/.bashhistory`, which might not be great; how about `gist --login-with-token` that presents you a UI to type the token in?
