### ISSUE TITLE
Add multiple files to single gist

### ISSUE THREAD

**Issue by ritiek** [defunkt/gist#265]
This tool is very handy. Thanks!

Is there a way to add multiple files to a gist? I created a gist but now I want to add another file to the same gist. Any plan on implementing this feature?

**Comment by ritiek** [comment]
Sorry, never mind. `gist -u <gist_url> test2.rb` does it.

**Comment by ConradIrwin** [comment]
Also `gist a.rb b.rb c.rb`ConradSent via SuperhumanOn Mon, Jun 19, 2017 at 2:23 AM, Ritiek Malhotra<notifications@github.com>wrote:Sorry, never mind. gist -u <gist_url> test2.rb does it.
