### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by KevinBatdorf** [defunkt/gist#272]
Using Ubuntu on Windows 10

`ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`

```sh
Obtaining OAuth2 access_token from github.
GitHub username: KevinBatdorf
GitHub password: /var/lib/gems/2.3.0/gems/gist-4.6.1/lib/gist.rb:336: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
```

After this it just hangs,

Thanks

**Comment by ConradIrwin** [comment]
Hi Kevin,

Did you type your password?

I'm not sure where those insecure world-writable warnings come from, but you're the second person to see one :/

Conrad

P.S. Superhuman is hiring iOS engineers — k now anyone? $1947 referral bonus. Learn more ( https://superhuman.com/jobs ). 

Sent via Superhuman ( https://sprh.mn/?vip=conrad@superhuman.com )

**Comment by KevinBatdorf** [comment]
Hi @ConradIrwin I just typed the password and it worked. I guess that's what it was waiting for :)
