### ISSUE TITLE
Update homebrew and rubygems to latest code, or update README

### ISSUE THREAD

**Issue by tdwalton** [defunkt/gist#273]
I got here from [https://github.com/defunkt/gist/issues/192](https://github.com/defunkt/gist/issues/192) because I was having the same issue, and was going to attempt to fix it and enter a PR, before discovering that the latest code works.

Homebrew  and rubygems.org are currently pinned to v4.6.1 which doesn't include a number of more recent changes, including [a fix for throttling on the read method](https://github.com/defunkt/gist/commit/0ad83ca286ba5443eb02f3bb862ce6c4e06668c3), without which I was unable to read *any* gists from our on-prem github enterprise.

I don't know if there are others out there attempting to use this tool installed via homebrew, or rubygems, but either they figured the problem out on their own and didn't bother to comment here, or they abandoned it, 'cause basic functionality was apparently broken.

It is possible the issue I encountered is due to a unique configuration of github enterprise and didn't affect a large number of github users. I didn't test extensively.

**Comment by tim-mc** [comment]
I don't really get the feeling that this is being actively maintained anymore...

**Comment by ConradIrwin** [comment]
Not really — would love a hand if you're up for it.

P.S. Superhuman is hiring iOS engineers — k now anyone? $1947 referral bonus. Learn more ( https://superhuman.com/jobs ). 

Sent via Superhuman ( https://sprh.mn/?vip=conrad@superhuman.com )

**Comment by tim-mc** [comment]
I think that would require giving access to cut a new release on Github, right?

**Comment by ConradIrwin** [comment]
ah ok, I didn't remember thats all that was left to do. v4.6.2 is pushed with the latest master.
