### ISSUE TITLE
Remove anonymous gist support

### ISSUE THREAD

**Issue by estebanz01** [defunkt/gist#275]
Per https://github.com/blog/2503-deprecation-notice-removing-anonymous-gist-creation this feature is going to be dead soon :disappointed: so I think it's important to remove this option altogether or mark it as deprecated (and maybe force the user to login?).

**Comment by ConradIrwin** [comment]
:(

P.S. Superhuman is hiring iOS engineers — k now anyone? $1947 referral bonus. Learn more ( https://superhuman.com/jobs ). 

Sent via Superhuman iOS ( https://sprh.mn/?vip=conrad@superhuman.com )

**Comment by domenkozar** [comment]
https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/ RIP
