### ISSUE TITLE
"tlsv1 alert protocol version" SSL error making gists

### ISSUE THREAD

**Issue by andlabs** [defunkt/gist#277]
OS X Sierra 10.12.6 (16G29)
gist v4.6.2 installed via homebrew just now (version db7f0734c)
custom OAuth token in `~/.gist`
I believe the ruby version is `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]` but I'm not sure if that's the one actually being used or just the one `/usr/bin/env ruby --version` in my shell reports

```
pietros-mbp:common pietro$ echo hi | gist
Error: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
```

Not sure what else to report about this issue; sorry.

**Comment by bgreen-litl** [comment]
I'm getting this too starting recently.

**Comment by gsnedders** [comment]
This is presumably [GitHub disabling](https://githubengineering.com/crypto-removal-notice/) TLSv1.0/1.1 as insecure.

**Comment by ConradIrwin** [comment]
You should be able to fix it by upgrading ruby, please let me know if that doesn't work

P.S. Superhuman is hiring iOS engineers — k now anyone? $1947 referral bonus. Learn more ( https://superhuman.com/jobs ). 

Sent via Superhuman ( https://sprh.mn/?vip=conrad@superhuman.com )

**Comment by andlabs** [comment]
Yep, `brew install ruby` and using that ruby fixed it. Thanks!

**Comment by andlabs** [comment]
Oops I must have reopened this by mistake

**Comment by pirates1010** [comment]
As a resource - run git --version and make sure it's somewhat recent, I had 1.9.x and it gave me that error until I updated to 2.x
