### ISSUE TITLE
Running into issues with gist for enterprise

### ISSUE THREAD

**Issue by kumarsiyer** [defunkt/gist#279]
Need help to fix this issue
```
/usr/local/bin/gist:146:in `parse': source '<html><body><h1>401 ' not in JSON! (JSON::ParserError)
	from /usr/local/bin/gist:987:in `parse'
	from /usr/local/bin/gist:1592:in `pretty_gist'
	from /usr/local/bin/gist:1574:in `get_gist_pages'
	from /usr/local/bin/gist:1509:in `list_all_gists'
	from /usr/local/bin/gist:2050:in `<main>'
```

**Comment by ConradIrwin** [comment]
@kumarsiyer I think you need to login, Github removed annonymous gisting, but I haven't updated this gem to handle the failure yet

P.S. Superhuman is hiring iOS engineers — k now anyone? $1947 referral bonus. Learn more ( https://superhuman.com/jobs ). 

Sent via Superhuman ( https://sprh.mn/?vip=conrad@superhuman.com )

**Comment by kumarsiyer** [comment]
I have logged in and received a new token but still receiving the same error.

**Comment by ConradIrwin** [comment]
@kumarsiyer not sure, can you access the github API from your terminal?

**Comment by kumarsiyer** [comment]
Only if I pass the username and password

**Comment by kumarsiyer** [comment]
Closing this issue. Looks like an internal problem with Enterprise Git, thanks for the quick response.
