### ISSUE TITLE
Cannot create anonymous gist after `gist --login`

### ISSUE THREAD

**Issue by branquito** [defunkt/gist#281]
After authorizing, I am not able to create gist via `gist -a -s`

I get this as a reponse: 
Error: Got Net::HTTPUnauthorized from gist: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}

I can however create gist using just `gist -s` without any problems

**Comment by ConradIrwin** [comment]
@branquito Unfortunately Github removed the ability to create anonymous gists, so we can no longer do this through the gem.

**Comment by wpcarro** [comment]
@ConradIrwin thanks for the explanation. That's too bad. Thoughts on removing this from the `help` message and Readme?

**Comment by ConradIrwin** [comment]
Please do!

Sent via Superhuman iOS ( https://sprh.mn/?vip=conrad.irwin@gmail.com )
