### ISSUE TITLE
anonymous option no longer works

### ISSUE THREAD

**Issue by alexreg** [defunkt/gist#286]
If I try to do `gist -a`, I get the following:

```
Traceback (most recent call last):
/usr/local/bin/gist:2021:in `<main>': invalid option: -ac (OptionParser::InvalidOption)
```

This option (anonymous gist) used to work, but no longer works. Was it removed for some reason? Could you possibly add it back?

**Comment by ConradIrwin** [comment]
Unfortunately GitHub removed the functionality: https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/ :(

**Comment by alexreg** [comment]
Ah, that's a shame. Fair enough though. There's still a small reference to it in the man page, maybe good to remove that. :-)

**Comment by JBallin** [comment]
@alexreg https://github.com/defunkt/gist/pull/288

**Comment by alexreg** [comment]
@JBallin Looks good, thanks.
