### ISSUE TITLE
Query parameter authentication is deprecated on GitHub

### ISSUE THREAD

**Issue by GiorgioGhisotti** [defunkt/gist#309]
Hello,

[GitHub has deprecated access token authentication through query parameters](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters). As far as I can tell this utility can't work with https authentication anymore short of asking the user for their credentials every time. Using ssh authentication could be a solution.

**Comment by ConradIrwin** [comment]
Are they continuing to support the Authorization: Bearer tokens?

P.S. Superhuman is hiring — referral bonus for Full Stack Engineers ( https://superhuman.com/roles?gh_jid=260350 ) : $1,947.

**Comment by Darkle** [comment]
They mention in the email to use the Authorization HTTP header instead FWIW

**Comment by cmoulliard** [comment]
The github email mentions the following message
```
Please use the Authorization HTTP header instead,
as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email ...

Visit 
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
for more information.
```

**Comment by GiorgioGhisotti** [comment]
As far as I can tell from the [documentation](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/), "basic authentication", even with OAuth, means that the user is queried for username and OAuth token _after_ making the http request - there may be a way to automate that process but it feels a bit clunky and not the intended way of authenticating.

**Comment by jcolson** [comment]
aren't they just saying use the header instead of the query parameter??

curl -H "Authorization: token OAUTH-TOKEN" https://api.github.com/user

like that?

**Comment by cmoulliard** [comment]
This command is working for me `curl -H "Authorization: token $GIT_TOKEN" https://api.github.com/gists/945a461e2abc33d222177a553bb1a0ae`

**Comment by GiorgioGhisotti** [comment]
Well in that case it should be pretty easy to fix, I didn't quite understand that prepending the token wold work.

**Comment by jcolson** [comment]
looks like it's already committed -> https://github.com/defunkt/gist/commit/635b1437a513e9a13367827ee3f74fbbdaa54aa8

**Comment by torarnv** [comment]
`brew unlink gist && brew install -s gist --HEAD` until brew has been updated

**Comment by typebrook** [comment]
> looks like it's already committed -> [635b143](https://github.com/defunkt/gist/commit/635b1437a513e9a13367827ee3f74fbbdaa54aa8)

@GiorgioGhisotti You can close this issue now
