### ISSUE TITLE
Terraform plan and strange gibberish at every line start

### ISSUE THREAD

**Issue by mkozjak** [defunkt/gist#348]
`terraform plan | gist -p`

produces

`
[0m[1mmodule.prometheus.module.ec2_...
`

For example

`
Changes to Outputs:
`
in regular stdout comes up as
`
[1mChanges to Outputs:[0m[0m
`
in gist.

**Comment by ConradIrwin** [comment]
These look like ANSI escape codes, which are used by shell commands to create colors (but are not parsed by gist, which expects plain text).

You should be able to remove them by running `terraform plan -no-color`: https://www.terraform.io/cli/commands/plan.

**Comment by mkozjak** [comment]
Thanks!!
